name: detect_object_moorcheh
description: This example showcases object detection within a live feed from a smartphone's camera.
ports:
- 8080
bricks:
- arduino:video_object_detection:
    devices:
    - remote_camera_0
- arduino:web_ui: {}
icon: 📽️
